matrix:
  include:
    - os: osx
      osx_image: xcode8
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang

language: c

branches:
  only:
    - release

env:
  global:
    - ARTIFACTS_DIRECTORY="build/release/"

cache:
  directories:
    - "$HOME/.electron"
    - "./node_modules"

before_install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | NVM_DIR=$HOME/.nvm sh
  - source $HOME/.nvm/nvm.sh
  - nvm install 6.6.0
  - nvm use 6.6.0

install:
  - npm install

before_script:
  - echo "Deploying artifacts from $ARTIFACTS_DIRECTORY"

script:
  - npm run build $TRAVIS_OS_NAME

after_success:
  - npm run-script deploy:github

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/24d905038aa07dda37df
    on_success: change
    on_failure: always
    on_start: never
